### ISSUE TITLE
Error reported in the background, but no effect

### ISSUE THREAD

**Issue by 1983378984** [dawson-vilamaa/BeaconWaypoints#13]
[16:17:14 WARN]: [BeaconWaypoints] Task #592786 for BeaconWaypoints v1.6.1 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_the_end
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.waypoints.WaypointHelper$1$1$1.run(WaypointHelper.java:161) ~[BeaconWaypoints-1.6.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by dawson-vilamaa** [comment]
Are you still having this error? And if so, how can I reproduce it?
