### ISSUE TITLE
Could not load 'plugins\BeaconWaypoints-1.6.3.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by nickchen0911** [dawson-vilamaa/BeaconWaypoints#18]
I do put the plugin in plugins file, but it doesn't work. 
I've tried many methods but still can't fix the problem

the error msg: 
[14:29:10 ERROR]: Could not load 'plugins\BeaconWaypoints-1.6.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:431) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3836-Bukkit-08ec344]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:213) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3836-Bukkit-08ec344]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:952) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3836-Bukkit-08ec344]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3836-Bukkit-08ec344]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at com.github.dawsonvilamaa.beaconwaypoint.Main.<init>(Main.java:37) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.lang.Class.newInstance(Class.java:685) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:143) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.github.dawsonvilamaa.beaconwaypoint.Main.<init>(Main.java:37) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.lang.Class.newInstance(Class.java:685) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:143) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 7 more

**Comment by dawson-vilamaa** [comment]
What server software are you using?
