### ISSUE TITLE
Unexpected token END OF FILE at position 0

### ISSUE THREAD

**Issue by StraXRobinark** [dawson-vilamaa/BeaconWaypoints#21]
**Describe the bug**
It says end of file and may sometimes even say no space left on device.

**To Reproduce**
Startup the Server

**Screenshots**
[18:24:43 INFO]: [BeaconWaypoints] Enabling BeaconWaypoints v1.6.3
[18:24:43 INFO]: [BeaconWaypoints] Loading module for version 1_20_R1
[18:24:43 WARN]: Unexpected token END OF FILE at position 0.
[18:24:43 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[18:24:43 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[18:24:43 WARN]:        at BeaconWaypoints-1.6.3.jar//com.github.dawsonvilamaa.beaconwaypoint.Main.loadData(Main.java:151)
[18:24:43 WARN]:        at BeaconWaypoints-1.6.3.jar//com.github.dawsonvilamaa.beaconwaypoint.Main.onEnable(Main.java:103)
[18:24:43 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[18:24:43 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[18:24:43 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:24:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:24:43 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562)
[18:24:43 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473)
[18:24:43 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[18:24:43 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[18:24:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[18:24:43 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[18:24:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[18:24:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Capture](https://github.com/dawson-vilamaa/BeaconWaypoints/assets/75534370/12f1feef-7490-401c-89cc-392386c33c2e)

**Comment by dawson-vilamaa** [comment]
Are any of the player files in plugins/BeaconWaypoints/players empty? There might be an issue when it's writing player data to the files, possibly because of there not being enough storage space to save to. Also, could you check if there are any errors when it's trying to save? That would be when the server shuts down, the plugin is reloaded, or every 5 minutes when it autosaves.

**Comment by StraXRobinark** [comment]
> 

I still have alot of storage space, there don't seem to be any issues with saving i think cause there were no messages that indicated anything wrong however it didn't mention saving either so idk.
