### ISSUE TITLE
1.19.2 doesn't work

### ISSUE THREAD

**Issue by Dettrane** [dawson-vilamaa/BeaconWaypoints#7]
The Plugin doesn't work on 1.19.2 somehow

**Comment by dawson-vilamaa** [comment]
What version of the plugin are you using? The latest one should be compatible with 1.19.2.

**Comment by Dettrane** [comment]
I am using the latest version, 1.5.0. I also have others plugins installed, maybe it could have to do with that.Am 16.12.2022 19:28 schrieb Dawson Vilamaa ***@***.***>:
What version of the plugin are you using? The latest one should be compatible with 1.19.2.

**Comment by dirtboll** [comment]
I was facing the same issue, but I'm on 1.19.3. I got this error when trying to load BeaconWaypoints.
```
[03:14:56] [Server thread/INFO]: Enabling BeaconWaypoints v1.5.0
[03:14:56] [Server thread/INFO]: [BeaconWaypoints] Loading module for version 1_19_R2
[03:14:56] [Server thread/ERROR]: Error occurred while enabling BeaconWaypoints v1.5.0 (Is it up to date?)
java.lang.IllegalStateException: BeaconWaypoints does not support server version "1_19_R2"
	at com.github.dawsonvilamaa.beaconwaypoint.version.VersionMatcher.match(VersionMatcher.java:15) ~[?:?]
	at com.github.dawsonvilamaa.beaconwaypoint.Main.onEnable(Main.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.dawsonvilamaa.beaconwaypoint.version.Version_1_19_R2
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.github.dawsonvilamaa.beaconwaypoint.version.VersionMatcher.match(VersionMatcher.java:11) ~[?:?]
	... 12 more
[03:14:56] [Server thread/INFO]: Disabling BeaconWaypoints v1.5.0
```
Since it said `1_19_R2`, I though it's related to this issue. I tried creating `Version_1_19_R2` class by copy-pasting `1_19_R1` and building it myself. It works like a charm.

**Comment by dawson-vilamaa** [comment]
@dirtboll I have not added support for 1.19.3 yet, but I plan on having it officially supported in the next couple weeks along with the other features I'm adding.

**Comment by Dettrane** [comment]
But my problem is it not working on 1.19.2. Just in case i have not noticed it, the plugin does work on Bukkit right?Am 18.12.2022 21:41 schrieb dirtboll ***@***.***>:
I was facing the same issue, but I'm on 1.19.3. I got this error when trying to load BeaconWaypoints.
[03:14:56] [Server thread/INFO]: Enabling BeaconWaypoints v1.5.0
[03:14:56] [Server thread/INFO]: [BeaconWaypoints] Loading module for version 1_19_R2
[03:14:56] [Server thread/ERROR]: Error occurred while enabling BeaconWaypoints v1.5.0 (Is it up to date?)
java.lang.IllegalStateException: BeaconWaypoints does not support server version "1_19_R2"
	at com.github.dawsonvilamaa.beaconwaypoint.version.VersionMatcher.match(VersionMatcher.java:15) ~[?:?]
	at com.github.dawsonvilamaa.beaconwaypoint.Main.onEnable(Main.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.dawsonvilamaa.beaconwaypoint.version.Version_1_19_R2
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.github.dawsonvilamaa.beaconwaypoint.version.VersionMatcher.match(VersionMatcher.java:11) ~[?:?]
	... 12 more
[03:14:56] [Server thread/INFO]: Disabling BeaconWaypoints v1.5.0

Since it said 1_19_R2, I though it's related to this issue. I tried creating Version_1_19_R2 class by copy-pasting 1_19_R1 and building it myself. It works like a charm.

**Comment by dawson-vilamaa** [comment]
I don't think I've tried using it with Bukkit, only with Spigot and Paper. Can you show any errors from the plugin that it has?

**Comment by Dettrane** [comment]
There are no errors, it just doesn't work.Am 19.12.2022 22:36 schrieb Dawson Vilamaa ***@***.***>:
I don't think I've tried using it with Bukkit, only with Spigot and Paper. Can you show any errors from the plugin that it has?

**Comment by dawson-vilamaa** [comment]
Can you give steps to reproduce the bug?
