### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Mooshed88** [dawson-vilamaa/BeaconWaypoints#8]
It's a great plugin but doesn't work on my server. (purpur 1.19)
When I click the beacon, I got this error
```
[11:47:09 ERROR]: Could not pass event InventoryClickEvent to BeaconWaypoints v1.5.0
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fA()'
        at com.github.dawsonvilamaa.beaconwaypoint.version.Version_1_19_R1.openBeaconMenu(Version_1_19_R1.java:37) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.gui.GUIs.lambda$beaconMenu$1(GUIs.java:57) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.gui.InventoryGUIButton.onClick(InventoryGUIButton.java:153) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.listeners.InventoryListener.onItemClick(InventoryListener.java:30) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1723]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:677) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3133) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.19.jar:git-Purpur-1723]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1723]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by dawson-vilamaa** [comment]
The latest version is not compatible with 1.19 because of the way Mojang structured the update to 1.19.1. Instead of adding a new version, they replaced the original 1.19 version, so I can only support 1.19 or 1.19.1, not both. You will either need to use the previous version of the plugin or update the server (this plugin doesn't support 1.19.3 currently).

**Comment by Mooshed88** [comment]
OK, thanks.
