### ISSUE TITLE
Can't beacon effect

### ISSUE THREAD

**Issue by Floodo** [dawson-vilamaa/BeaconWaypoints#9]
**Describe the bug**
The GUI isn't working for the first item (beacon) for changing effects. I can drop that beacon from GUI, and normally place it.

**To Reproduce**
1. Go to any beacon and open GUI (right click on beacon)
2. Click on 'Change beacon effects'
3. Drop that item from GUI
4. See error in console

**Expected behavior**
I could see the beacon affects and change it.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro, Java Paper 1.19 (with Geyser + waterfall)
 - Browser Chrome
 - Version 1.5.0

**Additional context**
[01:49:23 INFO]: Send: Could not pass event InventoryClickEvent to BeaconWaypoints v1.5.0
[01:49:23 ERROR]: Could not pass event InventoryClickEvent to BeaconWaypoints v1.5.0
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fA()'
        at com.github.dawsonvilamaa.beaconwaypoint.version.Version_1_19_R1.openBeaconMenu(Version_1_19_R1.java:37) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.gui.GUIs.lambda$beaconMenu$1(GUIs.java:57) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.gui.InventoryGUIButton.onClick(InventoryGUIButton.java:153) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.github.dawsonvilamaa.beaconwaypoint.listeners.InventoryListener.onItemClick(InventoryListener.java:30) ~[BeaconWaypoints-1.5.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor352.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3053) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Floodo** [comment]
I a few mintues ago downloaded a new version (1.6.0) and the same issue I have :((

**Comment by dawson-vilamaa** [comment]
Mojang/Spigot does not support 1.19 specifically, so you will need to upgrade your server to 1.19.1 or above.

**Comment by Floodo** [comment]
well, i dont want to upgrade the server, soo like could you add some code specially for 1.19, or remove it for 1.19? Because players can easily get beacons for free. :(
